mindmap
  root((/))
    about(about)
    admin(admin)
      admin_routes(routes)
    blog(blog)
      blog_slug[slug]
    boats(boats)
      boats_id[id]
    builder(builder)
    daily(daily)
      daily_latest(latest)
      daily_date[date]
        daily_section[section]
    entities(entities)
      entities_slug[slug]
    handicap
      estimate(estimate)
      intel(fleet-intel)
      phrf(phrf)
    submit(submit)
    support(support)
    supporters(supporters)
    weekly-edition(weekly-edition)
      weekly_date[date]
        weekly_section[section]
    api((api))
    next((_next))
